# Generated by Django 4.1.3 on 2022-11-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='added_at',
        ),
    ]
