# Generated by Django 4.1.3 on 2022-11-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
