# Generated by Django 4.1.3 on 2022-12-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_category_subscribers_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
